"""empty message

Revision ID: 4e530559b635
Revises: d78e4b4168d0
Create Date: 2026-03-28 10:18:16.335262

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4e530559b635'
down_revision: Union[str, Sequence[str], None] = 'd78e4b4168d0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('auth_user', 'is_verified')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('auth_user', sa.Column('is_verified', sa.BOOLEAN(), nullable=True))
    # ### end Alembic commands ###
