"""Add is_verified field to users

Revision ID: d78e4b4168d0
Revises: e77f42b253eb
Create Date: 2026-03-27 12:56:57.046844

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd78e4b4168d0'
down_revision: Union[str, Sequence[str], None] = 'e77f42b253eb'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('auth_user', sa.Column('is_verified', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('auth_user', 'is_verified')
    # ### end Alembic commands ###
