"""empty message

Revision ID: 0506195b32d9
Revises: 675b5c7ac3d4
Create Date: 2026-04-03 12:36:57.591499

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0506195b32d9'
down_revision: Union[str, Sequence[str], None] = '675b5c7ac3d4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('auth_user', 'phone_number')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('auth_user', sa.Column('phone_number', sa.VARCHAR(length=20), nullable=True))
    # ### end Alembic commands ###
